# Customer Life Time Value

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
#!pip install openpyxl

In [4]:
#Uncomment this line if using this notebook locally
#df = pd.read_excel('./data/retail/Online Retail.xlsx', sheet_name='Online Retail')

file_name = "data/OnlineRetail.xlsx"
df = pd.read_excel(file_name, sheet_name='Online Retail')

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [5]:
#df.tail()
df.shape

(541909, 8)

In [39]:
# Remove quantities that are less than 0 (possibly returned items)
df = df.loc[df['Quantity'] > 0]
df.shape

(380620, 9)

In [40]:
# Remove blank customer IDs
df = df[pd.notnull(df['CustomerID'])]

In [6]:
# View our data range
print('Date Range: %s to %s' % (df['InvoiceDate'].min(), df['InvoiceDate'].max()))

Date Range: 2010-12-01 08:26:00 to 2011-12-09 12:50:00

In [44]:
# taking all of the transactions that occurred before December 01, 2011 
df = df.loc[df['InvoiceDate'] < '2011-12-01']
print(df.loc[df['InvoiceDate'] < '2011-12-01'])

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
516364    579885    85034C          3 ROSE MORRIS BOXED CANDLES         4
516365    579885     21742          LARGE ROUND WICKER PLATTER          2
516366    579885     23084                   RABBIT NIGHT LIGHT         6
516367    579885     21257          VICTORIAN SEWING BOX MEDIUM         1
516368    579885     21259          VICTORIAN SEWING BOX SMALL          1

               InvoiceDate  UnitPrice  CustomerID         Country  Sales
0      2010-12-01 08:26:00       2.55     17850.0  United Kingdom  15.30
1      2010-12-01 08:26:00       3.39     17850.0  United Kingdom  20.34
2      2010-12-01 08:26:00       2.75     17850.0  United Kingdom  22.00
3      2010-12-01 08:26:00       3.39     17850.0  United Kingdom  20.34
4      2010-12-01 08:26:00       3.39     17850.0  United Kingdom  20.34
...                    ...        ...         ...             ...    ...
516364 2011-11-30 17:37:00       1.25     15444.0  United Kingdom   5.00
516365 2011-11-30 17:37:00       5.95     15444.0  United Kingdom  11.90
516366 2011-11-30 17:37:00       2.08     15444.0  United Kingdom  12.48
516367 2011-11-30 17:37:00       7.95     15444.0  United Kingdom   7.95
516368 2011-11-30 17:37:00       5.95     15444.0  United Kingdom   5.95

[380620 rows x 9 columns]

In [7]:
# Create a Sales Revenue Column
df['Sales'] = df['Quantity'] * df['UnitPrice']

In [8]:
# Get a orders summary dataset that shows the total in sales made per customer invoice
orders_df = df.groupby(['CustomerID', 'InvoiceNo']).agg({'Sales': sum,'InvoiceDate': max})

/tmp/ipykernel_331505/2523923102.py:2: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  orders_df = df.groupby(['CustomerID', 'InvoiceNo']).agg({'Sales': sum,'InvoiceDate': max})
/tmp/ipykernel_331505/2523923102.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  orders_df = df.groupby(['CustomerID', 'InvoiceNo']).agg({'Sales': sum,'InvoiceDate': max})

In [10]:
orders_df.head(10)

                         Sales         InvoiceDate
CustomerID InvoiceNo
12346.0    541431     77183.60 2011-01-18 10:01:00
12347.0    537626       711.79 2010-12-07 14:57:00
           542237       475.39 2011-01-26 14:30:00
           549222       636.25 2011-04-07 10:43:00
           556201       382.52 2011-06-09 13:01:00
           562032       584.91 2011-08-02 08:48:00
           573511      1294.32 2011-10-31 12:25:00
12348.0    539318       892.80 2010-12-16 19:09:00
           541998       227.44 2011-01-25 10:42:00
           548955       367.00 2011-04-05 10:47:00